services:
  dashboard:
    #image: labcapital/apps:stats_mantine
    build: .
    container_name: Gesco_VDOAP
    restart: unless-stopped
#    env_file:
#      - .env # Se espera que el .env tenga GITHUB_TOKEN=token
    ports:
      - "4280:1234"
    networks:
      - web_nginx

networks:
  web_nginx:
#    external: true
    driver: bridge
