services:
  dashboard:
    image: labcapital/apps:gesco_oap
    #build: .
    container_name: Gesco_VDOAP
    restart: unless-stopped
    ports:
      - "4280:1234"
    networks:
      - web_nginx

networks:
  web_nginx:
#    external: true
    driver: bridge
